export const HISTORY_BACK_ACTION_TYPE = "HISTORY_BACK_ACTION";
export const SELECT_VIEW_ACTION_TYPE = "SELECT_VIEW_ACTION";
export const SELECT_NAV_ELEMENT_ACTION_TYPE = "SELECT_NAV_ELEMENT_ACTION_TYPE";
